### ISSUE TITLE
学习交流

### ISSUE THREAD

**Issue by Lyndon-wong** [Enoryl/PanoSim#1]
你好！最近我也在学panosim，想用他生成一批仿真数据（可见光，目标3d位置，激光雷达点云pcd）。但是我对他插件里面的总线接口有点迷惑，可以交流一下吗？

**Comment by Enoryl** [comment]
你好！我主要是尝试用Panosim去获取行车过程中的图像数据以及对应时刻的速度、转向角信息，其他方面我并不了解（后来因为它难以获得稳定时间间隔的图像流之类的问题放弃使用了）。可以添加我的微信（微信号：Enoryl），我看看能不能帮你，如果你正在通过学校的一些渠道试用Panosim，我也可以把他的试用交流群分享给你，群里有Panosim官方的人员，给出的建议肯定比我好
